version: "3.9"

name: promptflow

services:
  core:
    build:
      context: .
      dockerfile: packages/core/Dockerfile
    env_file: [.env]
    environment:
      PY_RUNTIME_URL: http://python:8000
      JAVA_RUNTIME_URL: http://java:8080
      FLOW_PATH: /app/examples/flow.yaml
      FLOW_INPUT: ${FLOW_INPUT}
    depends_on:
      - python
      - java
    command: ["node", "dist/index.js"]
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3001:3001" # (옵션) 코어에 간단한 헬스엔드포인트 열어둠

  python:
    build:
      context: packages/runtimes/python
      dockerfile: Dockerfile
    env_file: [.env]
    # environment:
    #   OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"

  java:
    build:
      context: packages/runtimes/java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
