version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
  redis:
    image: redis:7-alpine
  python:
    build: ./packages/runtimes/python
  java:
    build: ./packages/runtimes/java
